declare module 'styled-components/native'
declare module 'youtube-music-api'
declare module 'lodash'
declare module 'react-native-animated-icons'
declare module 'react-native-ytdl'
declare module 'react-native-simple-bottom-sheet'
declare module 'react-native-marquee'
// declare module ''
// declare module ''
// declare module ''
// declare module ''
