export default [
    //
    // artists...
    //
    'Kishore Kumar',
    'Jubin Nautiyal',
    'Dhvani Bhanushali',
    'Guru Randhawa',
    'Arijit Singh',
    'Neha Kakkar',
    'Atif Aslam',
    'Rahat Fateh Ali Khan',
    'Sonu Nigam',
    'Sunidhi Chauhan',
    'Shreya Ghoshal',
    'Shaan',
    'Kanika Kapoor',
    'Ankit Tiwari',
    'B Praak',
    'Darshan Raval',
    'Asees Kaur',
    'Harrdy Sandhu',
    'Dhvani Bhanushali',
    'Millind Gaba',
    'Sunanda Sharma',
    'Stebin Ben',
    'Afsana Khan',
    'Raj Barman',
    'Rochak Kohli',
    'Mohit Chauhan',
    'A.R. Rahman',
    'Kumar Sanu',
    'Yo Yo Honey Singh',
    'Armaan Malik',
    'Pritam Chakraborty',
    'Badshah',
    'R.D. Burman',
    'Neeti Mohan',
    'Mika Singh',
    'Monali Thakur',
    'Tulsi Kumar',
    'Palak Muchhal',
    'Harshdeep Kaur',
    'Aditya Narayan',
    'Jasmin Walia',
    'Ed Sheeran',
    'Justin Bieber',
    'Dua Lipa',
    'Rihanna',
    'Adele',
    'Ariana Grande',
    'Eminem',
    'Taylor Swift',
    'Billie Eilish',
    'Shawn Mendes',
    'Selena Gomez',
    'Camila Cabello',
    'Beyoncé Knowles',
    'Lady Gaga',
    'Katy Perry',
    'Bruno Mars',
    'Post Malone',
    'Nick Jonas',
    'Imagine Dragons',
    //
    // search queries...
    //
    'new movies',
    'new remix',
    'hindi remakes',
    'hindi remake',
    'new hindi trendings',
    'most rated hindi songs',
    'most rated english songs',
    'most rated songs',
    'trending songs',
    'most viewed song on youtube',
    'bollywood romantic songs',
    'most listened romantic songs',
    'top new songs',
    'top hindi raps',
]
