export default [
    // hindi artists...
    'Kishore Kumar',
    'Alka Yagnik',
    'Udit Narayan',
    'Kumar Sanu',
    'Jubin Nautiyal',
    'Shilpi Raj',
    'Khesari Lal Yadav',
    'Lata Mangeshkar',
    'Arijit Singh',
    'Shreya Ghoshal',
    'Pawan Singh',
    'Neha Kakkar',
    'B Praak',
    'Asees Kaur',
    'Sonu Nigam',
    'Tanishk Bagchi',
    'Anuradha Paudwal',
    'Meet Bros',
    'Antra Singh Priyanka',
    'Badshah',
    'Atif Aslam',
    'Darshan Raval',
    'Tulsi Kumar',
    // english artists
    'Justin Beiber',
    'Marshmello',
    'Ariana Grande',
    'Eminem',
    'Ed Sheeran',
    'Taylor Swift',
    'Billie Eilish',
    'Katy Perry',
    'Alan Walker',
    'Rihanna',
    'Shawn Mendes',
    'Selena Gomez',
    'Imagine Dragons',
    'Doja Cat',
    'Dua Lipa',
    'Sia',
    'Shakira',
    // others
    'Blackpink',
    'BTS',
    // 'Kishore Kumar',
    // 'Lata Mangeshkar',
    // 'Mohammad Rafi',
    // 'Mukesh',
    // 'Geeta Dutt',
    // 'Talat Mahmood',
    // 'Asha Bhosle',
    // 'Hemanta Mukherjee',
    // 'Manna Dey',
    // 'Mahendra Kapoor',
    // 'Hariharan',
    // 'K.S. Chithra',
    // 'S.P. Balasubrahmanyam',
    // 'Anuradha Paudwal',
    // 'K.J. Yesudas',
    // 'Sadhana Sargam',
    // 'Kavita Krishnamurthy',
    // 'Udit Narayan',
    // 'Alka Yagnik',
    // 'Kumar Sanu',
    // 'Jubin Nautiyal',
    // 'Dhvani Bhanushali',
    // 'Guru Randhawa',
    // 'Arijit Singh',
    // 'Neha Kakkar',
    // 'Atif Aslam',
    // 'Rahat Fateh Ali Khan',
    // 'Sonu Nigam',
    // 'Sunidhi Chauhan',
    // 'Shreya Ghoshal',
    // 'Shaan',
    // 'Kanika Kapoor',
    // 'Ankit Tiwari',
    // 'B Praak',
    // 'Darshan Raval',
    // 'Asees Kaur',
    // 'Harrdy Sandhu',
    // 'Dhvani Bhanushali',
    // 'Millind Gaba',
    // 'Sunanda Sharma',
    // 'Stebin Ben',
    // 'Afsana Khan',
    // 'Raj Barman',
    // 'Rochak Kohli',
    // 'Mohit Chauhan',
    // 'Shankar Mahadevan',
    // 'Sachin Jigar',
    // 'A.R. Rahman',
    // 'Armaan Malik',
    // 'Pritam Chakraborty',
    // 'Badshah',
    // 'R.D. Burman',
    // 'Neeti Mohan',
    // 'Monali Thakur',
    // 'Tulsi Kumar',
    // 'Neha Bhasin',
    // 'Palak Muchhal',
    // 'Harshdeep Kaur',
    // 'Aditya Narayan',
    // 'Jasmin Walia',
    // 'Ed Sheeran',
    // 'Justin Bieber',
    // 'Dua Lipa',
    // 'Rihanna',
    // 'Adele',
    // 'Ariana Grande',
    // 'Eminem',
    // 'Taylor Swift',
    // 'Billie Eilish',
    // 'Shawn Mendes',
    // 'Selena Gomez',
    // 'Camila Cabello',
    // 'Beyoncé Knowles',
    // 'Lady Gaga',
    // 'Katy Perry',
    // 'Bruno Mars',
    // 'Post Malone',
    // 'Nick Jonas',
    // 'Imagine Dragons',
    // 'Shankar Ehsaan Loy',
    // 'Cardi B',
    // 'Sia',
    // 'Lauv',
    // 'Fifth Harmony',
    // 'Chainsmoker',
    // 'Akasa',
    // 'Jasleen Royal',
    // 'Tanishk Bagachi',
    // 'KK',
    // 'Salim Merchant',
    // 'Jonita Gandhi',
    // 'Vishal Dadlani',
    // 'Amit Trivedi',
    // 'Prateek Kuhad',
    // 'Black Pink',
    // 'BTS',
    // 'Michael Jackson',
    // 'Tupac Shakur',
    // 'Demi Lovato',
    // 'Drake',
    // 'Travis Scott',
    // 'Lil Wayne',
    // 'Kendrick Lamar',
    // // search queries...
    // 'new tracks',
    // 'new hits',
    // 'new movies',
    // 'new remix',
    // 'hindi remakes',
    // 'hindi remake',
    // 'new hindi trendings',
    // 'most rated hindi songs',
    // 'most rated english songs',
    // 'most rated songs',
    // 'trending songs',
    // 'most viewed song on youtube',
    // 'bollywood romantic songs',
    // 'most listened romantic songs',
    // 'top new songs',
    // 'top hindi raps',
    // 'top romantic songs',
    // 'best romantic songs',
    // 'party songs',
    // 'study songs',
    // 'new bollywood songs',
    // 'best boolywood trending',
    // 'trending hits',
    // 'pop',
    // 'chal ghar chalen',
    // 'most romantic songs',
    // 'romantic songs jukebox',
    // 'romantic songs mashup',
    // 'top romantic songs mashups',
    // 'top new romantic songs',
    // 'top new bollywood romantic songs',
    // 'most listened romantic songs',
    // 'most played romantic songs',
    // single songs only for testing purpose
    // 'Lut Gaye',
    // 'Wafa na raha',
]

const HINDI_QUERIES = []

const ENGLISH_QUERIES = []

const HINDI_ARTISTS_QUERIES = []

const ENGLISH_ARTISTS_QUERIES = []
