/**
 * THIS file will provide all those
 * constants which are realted to the name of screens throughout the application
 */

/**
 * screen in the profile stack
 */
export const PROFILE_STACK__MAIN_PROFILE_SCREEN =
    'PROFILE_STACK__MAIN_PROFILE_SCREEN'
export const PROFILE_STACK__SETTINGS_SCREEN = 'PROFILE_STACK__SETTINGS_SCREEN'
export const PROFILE_STACK__LANGUAGE_PICKER_SCREEN =
    'PROFILE_STACK__LANGUAGE_PICKER_SCREEN'
export const PROFILE_STACK__SETTINGS_UPDATER_SCREEN =
    'PROFILE_STACK__SETTINGS_UPDATER_SCREEN'
export const PROFILE_STACK__UPDATE_PROFILE_SCREEN =
    'PROFILE_STACK__UPDATE_PROFILE_SCREEN'
export const PROFILE_STACK__UPDATE_SOCIAL_MEDIA_LINKS_SCREEN =
    'PROFILE_STACK__UPDATE_SOCIAL_MEDIA_LINKS_SCREEN'

/**
 * authentication related screens
 */
export const AUTHENTICATION_STACK__REGISTER_SCREEN =
    'AUTHENTICATION_STACK__REGISTER_SCREEN'
export const AUTHENTICATION_STACK__LOGIN_SCREEN =
    'AUTHENTICATION_STACK__LOGIN_SCREEN'
export const AUTHENTICATION_STACK__FORGOT_PASSWORD_SCREEN =
    'AUTHENTICATION_STACK__FORGOT_PASSWORD_SCREEN'
export const AUTHENTICATION_STACK__OTP_SCREEN =
    'AUTHENTICATION_STACK__OTP_SCREEN'
