/**
 * THIS file will provide all those constants which are realted to the name of screens throughout the application
 */
export const PROFILE_STACK__MAIN_PROFILE_SCREEN = 'MAIN_PROFILE_SCREEN'
export const PROFILE_STACK__SETTINGS_SCREEN = 'SETTINGS_SCREEN'
export const PROFILE_STACK__LANGUAGE_PICKER_SCREEN = 'LANGUAGE_PICKER_SCREEN'
export const PROFILE_STACK__SETTINGS_UPDATER_SCREEN = 'SETTINGS_UPDATER_SCREEN'
export const PROFILE_STACK__UPDATE_PROFILE_SCREEN = 'UPDATE_PROFILE_SCREEN'
export const PROFILE_STACK__UPDATE_SOCIAL_MEDIA_LINKS_SCREEN =
    'UPDATE_SOCIAL_MEDIA_LINKS_SCREEN'
